import {Dimensions, StyleSheet} from 'react-native';
import {hScale, scale, wScale} from '@resolutions';
import {colors, fontSize} from '@themes';

const {height, width} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  containerSearch: {
    backgroundColor: colors.white,
    width: '100%',
    paddingBottom: scale(10),
    paddingTop: scale(10),
  },
  search: {
    marginHorizontal: scale(12),
  },
  scrollView: {
    backgroundColor: colors.graySystem2,
    height: '100%',
  },
  containerBody: {
    height: '100%',
  },
  imgEmpty: {
    alignSelf: 'center',
    marginTop: scale(24),
  },
  txtHeaderNodata: {
    color: colors.black,
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    alignSelf: 'center',
    lineHeight: scale(24),
    marginTop: scale(16),
  },
  txtContent: {
    marginTop: scale(4),
    alignSelf: 'center',
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: fontSize.size14,
    lineHeight: scale(22),
    color: '#525252',
  },
  imgEmpty: {
    alignSelf: 'center',
    marginTop: scale(24),
  },
  cardProgram: {
    backgroundColor: colors.white,
    marginHorizontal: scale(12),
    marginTop: scale(12),
    borderRadius: scale(8),
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    paddingHorizontal: scale(8),
  },
  headerProgram: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
    marginTop: scale(8),
  },
  containerBody: {
    flexDirection: 'row',
    marginBottom: scale(4),
  },
  txtProposal: {
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    color: colors.black,
  },
  bodyCard: {
    marginVertical: scale(8),
  },
  txtHeaderBody: {
    color: '#525252',
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    alignSelf: 'center',
    lineHeight: scale(22),
  },
  contentBody: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    alignSelf: 'center',
    lineHeight: scale(22),
    marginLeft: scale(4),
    width: '80%',
    overflow: 'hidden',
  },
  containerFooterCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: scale(8),
  },
  contentTimeApproval: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
  },
  bodyStatus: {
    borderRadius: scale(4),
    paddingHorizontal: scale(6),
    paddingVertical: scale(2),
    width: 'auto',
  },
  txtStatus: {
    fontSize: fontSize.size12,
    fontWeight: '500',
    lineHeight: scale(18),
    fontFamily: 'Inter-Medium',
  },
  btnAdd: {
    position: 'absolute',
    zIndex: 1,
    bottom: scale(16),
    right: scale(10),
    height: hScale(38),
    width: wScale(38),
    backgroundColor: colors.blue,
    borderRadius: scale(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  flatListContainer: {
    paddingBottom: scale(200),
  },
});

const stylesDetail = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    backgroundColor: colors.graySystem2,
    height: height,
  },
  flatScroll: {
    paddingBottom: scale(8),
  },
  containerBody: {
    height: height,
  },
  containerGeneralInfor: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  containerBodyCard: {
    marginBottom: scale(4),
    flex: 1,
  },
  cardProgram: {
    backgroundColor: colors.white,
    paddingHorizontal: scale(8),
    marginHorizontal: scale(12),
    borderRadius: scale(8),
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    marginTop: scale(8),
  },
  containerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  bodyCard: {
    marginVertical: scale(8),
  },
  txtHeaderBody: {
    color: '#6B7280',
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
  },
  contentBody: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
  },
  btnConfirm: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.blue,
    borderRadius: scale(8),
    height: hScale(38),
    width: '100%',
  },
  txtBtnConfirm: {
    color: colors.white,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
  },
  line: {
    borderTopWidth: scale(1),
    borderTopColor: colors.borderColor,
  },
  headerProgram: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
    marginTop: scale(8),
  },
  bodyStatus: {
    borderRadius: scale(4),
    paddingHorizontal: scale(6),
    paddingVertical: scale(2),
    width: 'auto',
    marginTop: scale(8),
  },
  txtStatus: {
    fontSize: fontSize.size12,
    fontWeight: '500',
    lineHeight: scale(18),
    fontFamily: 'Inter-Medium',
  },
  containerImage: {
    marginBottom: scale(8),
  },
});

const stylesProgress = StyleSheet.create({
  container: {
    flex: 1,
    padding: scale(16),
    backgroundColor: '#fff',
    height: height,
  },
  list: {
    paddingBottom: scale(16),
  },
  itemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  circle: {
    width: scale(16),
    height: scale(16),
    borderRadius: 10,
    backgroundColor: '#D1D3DB',
    position: 'absolute',
  },
  redCircle: {
    backgroundColor: 'red',
  },
  line: {
    width: scale(4),
    height: scale(50),
    backgroundColor: '#D1D3DB',
    position: 'absolute',
    left: scale(6),
    top: scale(22),
  },
  stopText: {
    marginLeft: scale(30),
    fontSize: fontSize.size14,
    fontWeight: '600',
    lineHeight: scale(22),
    fontFamily: 'Inter-Regular',
    color: colors.black,
  },
  boldText: {
    fontWeight: 'bold',
  },
  separator: {},
  txtDate: {
    marginTop: scale(8),
    fontSize: fontSize.size12,
    lineHeight: scale(18),
    fontFamily: 'Inter-Regular',
    color: colors.gray600,
    fontWeight: '400',
    marginLeft: scale(30),
    marginBottom: scale(4),
  },
  txtApprove: {
    fontSize: fontSize.size12,
    lineHeight: scale(18),
    fontFamily: 'Inter-Regular',
    color: colors.black,
    fontWeight: '400',
    marginLeft: scale(30),
    marginBottom: scale(8),
  },
});

const stylesFormOtherProposal = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    backgroundColor: colors.graySystem2,
    height: height,
  },
  flatScroll: {
    paddingBottom: scale(100),
  },
  header: {
    fontSize: fontSize.size16,
    fontWeight: '600',
    lineHeight: scale(24),
    fontFamily: 'Inter-SemiBold',
    color: colors.black,
    marginTop: scale(12),
    marginHorizontal: scale(12),
    marginBottom: scale(4),
  },
  card: {
    backgroundColor: colors.white,
    paddingBottom: scale(8),
    marginBottom: scale(8),
  },
  headerCard: {
    fontSize: fontSize.size14,
    fontWeight: '600',
    lineHeight: scale(22),
    fontFamily: 'Inter-SemiBold',
    color: colors.black,
    marginTop: scale(12),
    marginHorizontal: scale(12),
    marginBottom: scale(4),
  },
  inputAuto: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: scale(4),
  },
  inputRead: {
    width: '45%',
    marginHorizontal: scale(12),
    marginBottom: scale(8),
  },
  txtHeaderInputView: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
  },
  inputView: {
    borderRadius: scale(8),
    paddingLeft: scale(10),
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    marginTop: scale(8),
    borderWidth: scale(1),
    borderColor: '#D1D3DB',
    backgroundColor: '#E5E7EB',
    paddingVertical: scale(8),
    color: colors.black,
    overflow: 'hidden',
    height: hScale(42),
  },
  widthInput: {
    marginHorizontal: scale(12),
    flex: 1,
  },
  input: {
    marginHorizontal: scale(12),
    marginVertical: scale(4),
  },
  imgBox: {
    marginLeft: scale(12),
    marginTop: scale(8),
  },
  headerBoxImage: {
    fontSize: fontSize.size14,
    lineHeight: scale(22),
    fontFamily: 'Inter-Medium',
    fontWeight: '500',
    color: colors.black,
  },
  date: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnConfirm: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.blue,
    borderRadius: scale(8),
    height: hScale(38),
    marginHorizontal: scale(12),
    width: '48%',
  },
  txtBtnConfirm: {
    color: colors.white,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
  },
  btnSave: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: scale(8),
    height: hScale(38),
    width: '48%',
    borderColor: colors.borderColor,
    borderWidth: scale(1),
  },
  txtBtnSave: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
  },
  optionsModal: {
    margin: 0,
    justifyContent: 'flex-end',
    borderTopRightRadius: scale(8),
    borderTopLeftRadius: scale(8),
  },
  optionsModalContainer: {
    backgroundColor: colors.white,
    height: 'auto',
    borderTopRightRadius: scale(12),
    borderTopLeftRadius: scale(12),
  },
  contentContainer: {
    height: 'auto',
  },
  containerFile: {
    // padding: scale(8),
  },
  tableWrapper: {
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    borderRadius: scale(8),
    overflow: 'hidden',
    marginTop: scale(8),
  },
  confirmationButton: {
    borderRadius: scale(8),
    justifyContent: 'center',
    backgroundColor: colors.orange,
    marginTop: scale(25),
    marginBottom: scale(18),
    height: scale(45),
  },
  titleButton: {
    color: colors.white,
    fontWeight: '500',
    textAlign: 'center',
  },
  containerFileUpload: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: scale(12),
  },
  txtHeaderFile: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
    marginBottom: scale(4),
  },
  btnUploadFile: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderRadius: scale(6),
    marginTop: scale(12),
    borderWidth: scale(1),
    borderColor: colors.blue,
    width: 'auto',
    paddingHorizontal: scale(4),
  },
  txtBtnUploadFile: {
    color: colors.blue,
    fontSize: fontSize.size12,
    fontWeight: '400',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
    marginLeft: scale(4),
  },
  contentTime: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
  },

  containerFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    paddingVertical: scale(8),
    paddingHorizontal: scale(12),
    alignItems: 'center',
    zIndex: 1,
    flexDirection: 'row',
  },
  row: {
    flexDirection: 'row',
    backgroundColor: '#F9F9FB',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.borderColor,
  },
  rowTable: {
    flexDirection: 'row',
    borderWidth: scale(1),
    borderColor: colors.borderColor,
  },
});

export {styles, stylesDetail, stylesProgress, stylesFormOtherProposal};
