import {Dimensions, Platform, StyleSheet} from 'react-native';
import {hScale, scale, wScale} from '@resolutions';
import {colors, fontSize} from '@themes';

const {height, width} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  containerSearch: {
    backgroundColor: colors.white,
    width: '100%',
    paddingBottom: scale(10),
    paddingTop: scale(10),
  },
  search: {
    marginHorizontal: scale(12),
  },
  scrollView: {
    backgroundColor: colors.graySystem2,
    height: height,
  },
  containerBody: {
    height: '100%',
  },
  imgEmpty: {
    alignSelf: 'center',
    marginTop: scale(24),
  },
  txtHeaderNodata: {
    color: colors.black,
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    alignSelf: 'center',
    lineHeight: scale(24),
    marginTop: scale(16),
  },
  txtContent: {
    marginTop: scale(4),
    alignSelf: 'center',
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: fontSize.size14,
    lineHeight: scale(22),
    color: '#525252',
  },
  imgEmpty: {
    alignSelf: 'center',
    marginTop: scale(24),
  },
  cardProgram: {
    backgroundColor: colors.white,
    marginHorizontal: scale(12),
    marginTop: scale(12),
    borderRadius: scale(8),
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    paddingHorizontal: scale(8),
  },
  headerProgram: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
    marginTop: scale(8),
  },
  containerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  containerBody: {
    marginBottom: scale(4),
    flex: 1,
  },
  txtProposal: {
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    color: '#525252',
  },
  bodyCard: {
    marginVertical: scale(8),
  },
  txtHeaderBody: {
    color: '#6B7280',
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',

    lineHeight: scale(22),
  },
  contentBody: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
    width: '80%',
    overflow: 'hidden',
  },
  containerFooterCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: scale(8),
  },
  contentTimeApproval: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
  },
  bodyStatus: {
    borderRadius: scale(4),
    paddingHorizontal: scale(6),
    paddingVertical: scale(2),
    width: 'auto',
  },
  txtStatus: {
    fontSize: fontSize.size12,
    fontWeight: '500',
    lineHeight: scale(18),
    fontFamily: 'Inter-Medium',
  },
  btnAdd: {
    position: 'absolute',
    zIndex: 1,
    bottom: scale(Platform.OS === 'android' ? 16 : 40),
    right: scale(Platform.OS === 'android' ? 16 : 10),
    height: hScale(38),
    width: wScale(38),
    backgroundColor: colors.blue,
    borderRadius: scale(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  flatListContainer: {
    paddingBottom: scale(200),
  },
});

const stylesDetail = StyleSheet.create({
  container: {
    flex: 1,
  },
  containerFlat: {
    flex:1,paddingBottom:scale(100)
  },
   containerBodyCardView1: {
    justifyContent: 'center',
    //  alignItems: 'center',
    marginTop: scale(10),
    // alignContent: 'center',
    // alignSelf: 'center',
    // width: scale(320 / 2),
  },
  containerBodyCardView: {
    justifyContent: 'center',
    //  alignItems: 'center',
    marginTop: scale(10),
    // alignContent: 'center',
    // alignSelf: 'center',
    width: scale(320 / 2),
  },
  containerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',marginHorizontal:scale(12)
  },
  headerProgram: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
    marginTop: scale(8),
    // textAlign: 'center',
  },
  scrollView: {
    height: '100%',
    backgroundColor: colors.graySystem2,
  },
  containerBody: {
    flexGrow: 1,
    paddingBottom: scale(200),
  },
  cardProgram: {
    backgroundColor: colors.white,
    paddingHorizontal: scale(12),
    paddingBottom: scale(8),
  },
  headerModalApproval: {
    color: colors.black,
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(24),
    marginVertical: scale(8),
    textAlign: 'center',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.borderColor,
    paddingVertical: scale(8),
  },
  containerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  header: {
    fontSize: fontSize.size16,
    fontWeight: '600',
    lineHeight: scale(24),
    fontFamily: 'Inter-SemiBold',
    color: colors.black,
    marginTop: scale(12),
    marginHorizontal: scale(12),
    marginBottom: scale(4),
  },
  btnShowInfor: {
    marginRight: scale(12),
  },
  card: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: scale(10),
    alignItems: 'center',
    width: '55%',
  },
  headerInput: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
    marginBottom: scale(4),
    marginHorizontal: scale(12),
  },
  inputNote: {
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    paddingHorizontal: scale(8),
    paddingVertical: scale(12),
    borderRadius: scale(8),
    fontSize: fontSize.size14,
    lineHeight: scale(22),
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    color: colors.black,
    textAlignVertical: 'top',
    backgroundColor: '#F9FAFB',
    marginTop: scale(8),
    marginHorizontal: scale(12),
  },
  containerFooter: {
    position: 'absolute',
    bottom: scale(Platform.OS === 'android' ? 0 : 0),
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    paddingVertical: scale(8),
    paddingHorizontal: scale(12),
    alignItems: 'center',
    zIndex: 10,
    borderTopWidth: scale(1),
    borderTopColor: colors.borderColor,
  },
  btnFooter: {
    backgroundColor: colors.blue,
    height: hScale(38),
    width: '100%',
    justifyContent: 'center',
    alignContent: 'center',
    borderRadius: scale(8),
    marginBottom: scale(Platform.OS === 'android' ? 0 : 16),
  },
  txtBtnFooter: {
    fontSize: fontSize.size16,
    lineHeight: scale(24),
    fontFamily: 'Inter-SemiBold',
    fontWeight: '600',
    color: colors.white,
    textAlign: 'center',
  },
  optionsModal: {
    margin: 0,
    height: 'auto',
    justifyContent: 'flex-end',
    borderTopRightRadius: scale(8),
    borderTopLeftRadius: scale(8),
  },
  optionsModalContainer: {
    backgroundColor: colors.white,
    height: 'auto',
    borderTopRightRadius: scale(12),
    borderTopLeftRadius: scale(12),
  },
  headerModal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.graySystem2,
    backgroundColor: colors.white,
    borderTopLeftRadius: scale(12),
    borderTopRightRadius: scale(12),
    marginHorizontal: scale(12),
  },
  containerFooterModal: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    paddingHorizontal: scale(16),
    zIndex: 1,
    borderTopWidth: scale(1),
    borderTopColor: colors.borderColor,
    borderTopColor: colors.borderColor,
  },
  btnFooterModal: {
    backgroundColor: colors.green,
    borderRadius: scale(8),
    height: hScale(38),
    marginTop: scale(12),
    marginBottom: scale(Platform.OS === 'ios' ? 24 : 12),
    justifyContent: 'center',
    alignContent: 'center',
  },
  txtBtnFooterModal: {
    color: colors.white,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
    textAlign: 'center',
  },
  cardProgramModal: {
    backgroundColor: colors.white,
    paddingBottom: scale(80),
  },
  input: {
    flex: 1,
    marginHorizontal: scale(12),
  },
  containerBodyCard: {
    flex: 1,
    marginBottom: scale(8),
  },
  txtHeaderBody: {
    color: '#6B7280',
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
  },
  mrh60: {height: scale(60), width: '100%'},
  contentBody: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
  },
  cardCustomer: {
    backgroundColor: colors.white,
    paddingHorizontal: scale(8),
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    borderRadius: scale(8),
    marginVertical: scale(8),
    paddingVertical: scale(8),
  },
  contentCard: {
    marginBottom: scale(8),
    width: scale(300 / 2),
  },
  contentCard1: {
    marginBottom: scale(8),
  },
  txtHeaderCard: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(18),
    marginBottom: scale(8),
  },
});

const stylesProgress = StyleSheet.create({
  container: {
    flex: 1,
    padding: scale(16),
    backgroundColor: '#fff',
    height: height,
  },
  list: {
    paddingBottom: scale(16),
  },
    list1: {
    paddingBottom: scale(70),
  },
  itemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  circle: {
    width: scale(16),
    height: scale(16),
    borderRadius: 10,
    backgroundColor: '#D1D3DB',
    position: 'absolute',
  },
  line: {
    width: scale(4),
    height: scale(50),
    backgroundColor: '#D1D3DB',
    position: 'absolute',
    left: scale(6),
    top: scale(22),
  },
  stopText: {
    marginLeft: scale(30),
    fontSize: fontSize.size14,
    fontWeight: '600',
    lineHeight: scale(22),
    fontFamily: 'Inter-Regular',
    color: colors.black,
  },
  separator: {},
  txtDate: {
    marginTop: scale(8),
    fontSize: fontSize.size12,
    lineHeight: scale(18),
    fontFamily: 'Inter-Regular',
    color: colors.gray600,
    fontWeight: '400',
    marginLeft: scale(30),
    marginBottom: scale(4),
  },
  txtApprove: {
    fontSize: fontSize.size12,
    lineHeight: scale(18),
    fontFamily: 'Inter-Regular',
    color: colors.black,
    fontWeight: '400',
    marginLeft: scale(30),
    marginBottom: scale(8),
  },
});

const stylesFormCusClosedMove = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    backgroundColor: colors.graySystem2,
    height: height,
  },
  card: {
    backgroundColor: colors.white,
    paddingBottom: scale(8),
  },
  inputAuto: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: scale(4),
  },
  widthInput: {
    flex: 1,
    marginHorizontal: scale(12),
  },
  input: {
    marginHorizontal: scale(12),
    marginVertical: scale(4),
  },
  btnConfirm: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.blue,
    borderRadius: scale(8),
    height: hScale(38),
    marginHorizontal: scale(12),
    width: '48%',
    marginBottom: scale(Platform.OS === 'ios' ? 16 : 0),
  },
  txtBtnConfirm: {
    color: colors.white,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
  },
  btnSave: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: scale(8),
    height: hScale(38),
    width: '48%',
    borderColor: colors.borderColor,
    borderWidth: scale(1),
    marginBottom: scale(Platform.OS === 'ios' ? 16 : 0),
  },
  txtBtnSave: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
  },
  containerFooter: {
    position: 'absolute',
    bottom: Platform.OS === 'android' ? 0 : scale(0),
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    paddingHorizontal: scale(12),
    paddingVertical: scale(8),
    flexDirection: 'row',
    zIndex: 1,
    borderTopWidth: scale(1),
    borderTopColor: colors.borderColor,
  },
  header: {
    fontSize: fontSize.size16,
    fontWeight: '600',
    lineHeight: scale(24),
    fontFamily: 'Inter-SemiBold',
    color: colors.black,
    marginHorizontal: scale(12),
  },
  btnShowInfor: {
    marginRight: scale(12),
  },
  btnAdd: {
    borderWidth: scale(1),
    borderColor: colors.blue,
    paddingBottom: scale(3),
    borderRadius: scale(4),
    marginRight: scale(12),
    paddingHorizontal: scale(8),
    paddingTop: scale(5),
  },
  txtAdd: {
    color: colors.blue,
    fontSize: fontSize.size12,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(12),
  },
  containerHeader: {
    alignContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: scale(8),
  },
  imgBox: {
    marginLeft: scale(12),
    marginTop: scale(8),
  },
  headerBoxImage: {
    fontSize: fontSize.size14,
    lineHeight: scale(22),
    fontFamily: 'Inter-Medium',
    fontWeight: '500',
    color: colors.black,
  },
});

export {styles, stylesDetail, stylesProgress, stylesFormCusClosedMove};
