import {StyleSheet, Dimensions, Platform} from 'react-native';

import {colors, fontSize} from '../../themes';
import {hScale, scale, wScale} from '../../utils/resolutions';

const {height, width} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    backgroundColor: colors.graySystem2,
    height: height,
    width: '100%',
  },
  img: {
    width: wScale(64),
    height: hScale(64),
  },
  containerBody: {
    marginTop: scale(16),
    marginHorizontal: scale(16),
  },
  txtTitleItem: {
    color: colors.black,
    fontSize: fontSize.size16,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(24),
  },
  txtItem: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
  },
  txtItem_2: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
  },
  txtItem_3: {
    color: '#6B7280',
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
  },
  item_2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#D1D3DB',
    marginHorizontal: scale(16),
    paddingTop: scale(13),
    paddingBottom: scale(13),
  },
  item_3: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: scale(16),
    paddingTop: scale(13),
    paddingBottom: scale(13),
  },
  item: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: scale(16),
    paddingTop: scale(16),
    paddingBottom: scale(8),
  },
  itemBody: {
    flexDirection: 'row',
  },
  itemBody_two: {
    flexDirection: 'row',
    marginTop: scale(16),
    marginHorizontal: scale(16),
    backgroundColor: colors.white,
    paddingHorizontal: scale(16),
    paddingVertical: scale(16),
    borderRadius: scale(12),
    alignContent: 'center',
  },
  containerItem: {
    marginLeft: scale(12),
  },
  headerItem: {
    backgroundColor: colors.white,
    borderRadius: scale(12),
  },
  bodyInput: {
    marginTop: scale(8),
    marginHorizontal: scale(16),
  },
  row: {
    borderRadius: scale(12),
    backgroundColor: colors.white,
  },
  row_two: {
    borderRadius: scale(12),
    backgroundColor: colors.white,
    paddingHorizontal: scale(16),
    paddingTop: scale(8),
  },
  card: {
    flexDirection: 'row',
    paddingVertical: scale(10),
    borderBottomWidth: 1,
    borderBottomColor: '#D1D3DB',
    marginHorizontal: scale(16),
  },
  cardNoBorder: {
    flexDirection: 'row',
    paddingVertical: scale(10),
    marginHorizontal: scale(16),
  },
  title: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    marginLeft: scale(12),
  },
  line: {
    borderBottomWidth: 1,
    borderBottomColor: '#D1D3DB',
    marginBottom: scale(8),
  },
  txtContent: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
  },
  txtHeader_two: {
    color: '#6B6F80',
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
  },
  itemInfo: {
    marginTop: scale(16),
    marginBottom: scale(8),
  },
  contentInfo: {
    marginBottom: scale(8),
  },
  contentInfoBottom: {
    marginBottom: scale(16),
  },
  inputTwo: {
    marginTop: scale(8),
  },
  circle: {
    marginHorizontal: scale(4),
    backgroundColor: colors.black,
    width: wScale(5),
    height: hScale(5),
    borderRadius: scale(5),
    top: scale(10),
  },
  btnAdd: {
    width: width - 32,
    height: hScale(48),
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: scale(16),
    borderRadius: scale(16),
    marginTop: scale(8),
    borderWidth: 1,
    borderColor: colors.orange,
  },
  txtAdd: {
    color: colors.orange,
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(24),
  },
  containerButton: {
    flexDirection: 'row',
    marginTop: scale(8),
  },
  containerHeader_two: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: scale(16),
    marginHorizontal: scale(16),
  },
  itemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  txtItemHeader: {
    fontFamily: 'Inter-SemiBold',
    fontWeight: '600',
    fontSize: fontSize.size12,
    lineHeight: scale(18),
    color: colors.blue,
    marginRight: scale(6),
  },
  header: {
    fontFamily: 'Inter-SemiBold',
    fontWeight: '600',
    fontSize: fontSize.size16,
    lineHeight: scale(24),
    color: colors.black,
  },
  rowContainer_two: {
    backgroundColor: colors.white,
    marginHorizontal: scale(16),
    borderRadius: scale(12),
    marginTop: scale(8),
  },
  cardHeader: {
    fontFamily: 'Inter-SemiBold',
    fontWeight: '600',
    fontSize: fontSize.size16,
    lineHeight: scale(24),
    color: colors.black,
    paddingHorizontal: scale(16),
    paddingVertical: scale(8),
    width: '90%',
  },
  containerHeaderItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '70%',
  },

  inputBottom: {
    marginBottom: scale(100),
  },
  flatlist: {
    marginBottom: scale(100),
  },
  optionsModal: {
    margin: 0,
  },
  optionsModalContainer: {
    height: hScale(180),
    backgroundColor: colors.graySystem2,
    borderRadius: scale(12),
    marginHorizontal: scale(16),
  },
  headerContent_gray: {
    flexDirection: 'row',
    alignItems: 'center',
    height: hScale(46),
    paddingHorizontal: scale(16),
    backgroundColor: colors.graySystem2,
    borderTopLeftRadius: scale(24),
    borderTopRightRadius: scale(24),
  },
  contentBody: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: scale(5),
  },
  titleModalThank: {
    color: '#0C2D57',
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(24),
    textAlign: 'center',
    left: width / 2 - 90,
  },
  titleContent: {
    color: '#0C2D57',
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(24),
    textAlign: 'center',
  },
  titleContentName: {
    color: '#0C2D57',
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(24),
    textAlign: 'center',
  },
  btn: {
    height: hScale(48),
    width: wScale(140),
    backgroundColor: colors.white,
    borderWidth: scale(1),
    borderColor: '#E5E6EB',
    borderRadius: scale(12),
    justifyContent: 'center',
    alignItems: 'center',
  },
  txtBtn: {
    color: colors.black,
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(24),
    textAlign: 'center',
  },
  txtBtnDeleteModal: {
    color: colors.white,
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(24),
    textAlign: 'center',
  },
  content: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginHorizontal: scale(16),
    width: '90%',
  },
  btnChangePass: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: scale(8),
    height: hScale(38),
    backgroundColor: colors.blue,
    width: '100%',
    marginBottom: scale(Platform.OS === 'ios' ? 16 : 0),
  },
    btnChangePass1: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: scale(8),
    height: hScale(38),
    backgroundColor: colors.blue,
    width: '100%',
    marginBottom: scale(Platform.OS === 'ios' ? 0 : 0),
  },
  textChangePass: {
    color: colors.white,
    fontWeight: '600',
    fontSize: fontSize.size16,
    fontFamily: 'Inter-SemiBold',
    fontStyle: 'normal',
  },
  txtLanguage: {
    color: '#6B7280',
    fontWeight: '400',
    fontSize: fontSize.size14,
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    marginRight: scale(4),
  },
  btnLanguage: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  safeArea: {
    flex: 1,
  },
  footer: {
    paddingHorizontal: scale(12),
    paddingVertical: scale(8),
    backgroundColor: colors.white,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
    footer1: {
    paddingHorizontal: scale(12),
    paddingTop: scale(8),
    backgroundColor: colors.white,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  btnLogout: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: scale(8),
    height: hScale(38),
    backgroundColor: colors.white,
    marginTop: scale(16),
    borderWidth: scale(1),
    borderColor: colors.red,
  },
  textLogoutBtn: {
    color: colors.red,
    fontWeight: '600',
    fontSize: fontSize.size16,
    fontFamily: 'Inter-SemiBold',
    fontStyle: 'normal',
  },
  imgBox: {
    marginLeft: scale(16),
  },
  body_footer: {
    paddingBottom: scale(10),
    marginTop: scale(12),
    paddingTop: scale(4),
    marginBottom: scale(100),
  },
  input: {
    marginTop: scale(12),
  },
  labeAttach: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
  },
  btnCancel: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: scale(8),
    height: hScale(38),
    width: '48%',
    backgroundColor: colors.white,
    borderWidth: scale(1),
    borderColor: '#D1D5DB',
  },
  textCancel: {
    color: colors.black,
    fontWeight: '600',
    fontSize: fontSize.size16,
    fontFamily: 'Inter-SemiBold',
    fontStyle: 'normal',
  },
  btnSave: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: scale(8),
    height: hScale(38),
    width: '48%',
    backgroundColor: colors.blue,
  },
  headerGradient: {
    height: hScale(300),
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: hScale(140),
    flex: 1,
    width: '100%',
  },
  headerContent: {
    alignItems: 'center',
    backgroundColor: colors.white,
    width: '100%',
  },
    headerContentnew: {
    alignItems: 'center',
    backgroundColor: colors.graySystem2,
    width: '100%',
  },
  avatar: {
    width: wScale(80),
    height: hScale(80),
    borderRadius: scale(42),
    borderWidth: scale(1),
    borderColor: colors.white,
    marginBottom: scale(200),
  },
  viewavatar: {
    width: wScale(80),
    height: hScale(80),
    borderRadius: scale(40),
    borderWidth: scale(0),
    borderColor: colors.white,
    marginBottom: scale(12),
    position: 'absolute',
    top: -scale(40),
  },
  userName: {
    color: colors.black,
    fontWeight: '600',
    fontSize: fontSize.size20,
    fontFamily: 'Inter-SemiBold',
    fontStyle: 'normal',
    lineHeight: scale(26),
    marginTop: scale(12),
  },
  companyName: {
    color: '#525252',
    fontWeight: '500',
    fontSize: fontSize.size14,
    fontFamily: 'Inter-Medium',
    fontStyle: 'normal',
    lineHeight: scale(22),
    marginTop: scale(4),
    marginBottom: scale(12),
    marginHorizontal:scale(16)
  },
  bodyContainer: {
    backgroundColor: colors.white,
    flex: 1,
    width: '100%',
    paddingTop: scale(12),
  },
  sectionTitle: {
    fontSize: fontSize.size16,
    fontWeight: '600',
    color: colors.black,
    marginLeft: scale(16),
    marginBottom: scale(12),
  },
  settingGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: scale(16),
  },
  settingItem: {
    width: '22%',
    aspectRatio: 1,
    borderRadius: scale(16),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: scale(12),
  },
  settingText: {
    fontSize: fontSize.size12,
    fontWeight: '500',
    color: colors.black,
    textAlign: 'center',
    marginTop: scale(6),
  },
  mrh8: {
    height: scale(10),
    width: '100%',
    backgroundColor: '#F5F5F5',
  },
  scrollContainer: {
    paddingBottom: scale(12),
  },
  wrapper: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    paddingHorizontal: scale(4),
  },
  item3: {
    width: '25%', // để 4 cột
    alignItems: 'center',
    marginBottom: scale(20),
  },
  iconContainer: {
    width: scale(46),
    height: scale(46),
    borderRadius: scale(16),
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: scale(8),
  },
  text: {
    fontSize: fontSize.size10,
    color: '#000',
    textAlign: 'center',
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(15),
  },
  modal: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  headerModal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.gray300,
    backgroundColor: colors.white,
    borderTopLeftRadius: scale(12),
    borderTopRightRadius: scale(12),
    paddingTop: scale(10),
    paddingBottom: scale(6),
    paddingHorizontal: scale(12),
  },
  titleModal: {
    fontFamily: 'Inter-SemiBold',
    fontSize: fontSize.size16,
    lineHeight: scale(24),
    fontWeight: '600',
    color: colors.black,
    flex: 1,
    textAlign: 'center',
  },
  viewModalNN: {
    marginBottom: scale(100),
  },
  btnMenu: {
    position: 'absolute',
    left: scale(8),
    top: scale(50),
    padding: scale(8),
  },
});
