import {Dimensions, Platform, StyleSheet} from 'react-native';
import {hScale, scale, wScale} from '@resolutions';
import {colors, fontSize} from 'themes';

const {height, width} = Dimensions.get('window');
import {useSafeAreaInsets} from 'react-native-safe-area-context';
//  const insets = useSafeAreaInsets();
const styles = StyleSheet.create({
  container: {
    flex: 1,
    // marginBottom: scale(insets.bottom),
  },
  containerSearch: {
    backgroundColor: colors.white,
    width: '100%',
    paddingBottom: scale(10),
    paddingTop: scale(10),
  },
  search: {
    marginHorizontal: scale(12),
  },
  scrollView: {
    backgroundColor: colors.graySystem2,
    height: height,
  },
  containerBody: {
    height: '100%',
  },
  btnAdd: {
    position: 'absolute',
    zIndex: 1,
    top: height - 50,
    right: scale(10),
    height: hScale(38),
    width: wScale(38),
    backgroundColor: colors.blue,
    borderRadius: scale(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerBody: {
    flexDirection: 'row',
    marginHorizontal: scale(8),
    marginBottom: scale(4),
  },
  icon: {
    top: scale(4),
  },
  contentBody: {
    fontSize: fontSize.size14,
    fontWeight: '400',
    lineHeight: scale(22),
    fontFamily: 'Inter-Regular',
    color: colors.black,
    marginLeft: scale(4),
    overflow: 'hidden',
    width: '90%',
  },
  contentBody1: {
    fontSize: fontSize.size14,
    fontWeight: '500',
    lineHeight: scale(22),
    fontFamily: 'Inter-Medium',
    color: colors.black,
    marginLeft: scale(4),
    overflow: 'hidden',
    width: '90%',
  },
  cardProgram: {
    backgroundColor: colors.white,
    marginHorizontal: scale(12),
    marginTop: scale(12),
    borderRadius: scale(8),
    borderWidth: scale(1),
    borderColor: colors.borderColor,
  },
  itemBody_two: {
    flexDirection: 'row',
    padding: scale(8),
    borderRadius: scale(12),
  },
  containerItem: {
    marginLeft: scale(8),
    width: width - scale(60),
  },
  img: {
    width: wScale(46),
    height: hScale(46),
  },
  imgavatar: {
    width: wScale(46),
    height: hScale(46),
    borderRadius: wScale(23),
    resizeMode: 'cover',
  },
  containerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  containerStatus: {
    flexDirection: 'row',
  },
  txtTitleItem: {
    fontSize: fontSize.size16,
    fontWeight: '600',
    lineHeight: scale(24),
    fontFamily: 'Inter-SemiBold',
    color: colors.black,
  },
  bodyStatus: {
    borderRadius: scale(6),
    paddingHorizontal: scale(6),
    paddingVertical: scale(2),
    marginRight: scale(8),
    width: 'auto',
  },
  txtStatus: {
    fontSize: fontSize.size12,
    fontWeight: '500',
    lineHeight: scale(18),
    fontFamily: 'Inter-Medium',
  },
  btnAdd: {
    position: 'absolute',
    zIndex: 1,
    bottom: scale(Platform.OS === 'ios' ? 40 : 16),
    right: scale(Platform.OS === 'ios' ? 16 : 10),
    height: hScale(38),
    width: wScale(38),
    backgroundColor: colors.blue,
    borderRadius: scale(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  flatListContainer: {
    paddingBottom: scale(259),
  },
  txtHeaderNodata: {
    color: colors.black,
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    alignSelf: 'center',
    lineHeight: scale(24),
    marginTop: scale(16),
  },
  txtContent: {
    marginTop: scale(4),
    alignSelf: 'center',
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: fontSize.size14,
    lineHeight: scale(22),
    color: '#525252',
  },
  imgEmpty: {
    alignSelf: 'center',
    marginTop: scale(24),
  },
  optionsModal: {
    margin: 0,
    justifyContent: 'flex-end',
  },
  optionsModalContainer: {
    height: 'auto',
  },
  contentContainer: {
    backgroundColor: colors.white,
    height: 'auto',
  },
  headerContent_gray: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    height: hScale(46),
    paddingHorizontal: scale(16),
    backgroundColor: colors.white,
    borderTopLeftRadius: scale(24),
    borderTopRightRadius: scale(24),
    borderBottomWidth: scale(1),
    borderBottomColor: colors.borderColor,
  },
  titleModal: {
    color: colors.black,
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(24),
    textAlign: 'center',
    flex: 1,
  },
  containerRadio: {
    marginHorizontal: scale(16),
  },
  card: {
    flexDirection: 'row',
    paddingVertical: scale(12),
    alignItems: 'center',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.borderColor,
  },
  cardNoBorder: {
    flexDirection: 'row',
    paddingVertical: scale(12),
    alignItems: 'center',
    borderBottomWidth: scale(0),
  },
  title: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    width: '90%',
    marginLeft: scale(12),
  },
  containerFooter: {
    backgroundColor: colors.white,
    padding: scale(8),
    alignItems: 'center',
    flexDirection: 'row',
    borderTopWidth: scale(1),
    borderTopColor: colors.borderColor,
  },
  btnConfirm: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.green,
    borderRadius: scale(8),
    height: hScale(38),
    marginHorizontal: scale(12),
    width: '48%',
  },
  txtBtnConfirm: {
    color: colors.white,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
  },
  btnClear: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: scale(8),
    height: hScale(38),
    width: '48%',
    borderColor: colors.borderColor,
    borderWidth: scale(1),
  },
  txtBtnClear: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: scale(16),
  },

  modalContent: {
    width: width - scale(24), // phù hợp với margin horizontal của container
    maxHeight: height * 0.8, // không to hơn màn hình
    backgroundColor: colors.white,
    borderRadius: scale(12),
    paddingHorizontal: scale(12),
    paddingVertical: scale(14),
    // shadow (android + ios)
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: scale(6),
    elevation: 6,
  },

  modalTitle: {
    fontSize: fontSize.size16 || 18,
    fontWeight: '700',
    marginBottom: scale(8),
    color: colors.black,
    textAlign: 'left',
  },

  sectionTitle: {
    marginTop: scale(10),
    fontWeight: '600',
    fontSize: fontSize.size14 || 14,
    color: colors.black,
  },

  sectionText: {
    fontSize: fontSize.size14,
    color: colors.black,
    lineHeight: scale(20),
    marginTop: scale(4),
  },

  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginTop: scale(16),
    // backgroundColor: 'red',
  },

  btnPrimary: {
    paddingVertical: hScale(8),
    paddingHorizontal: wScale(14),
    borderRadius: scale(8),
    marginLeft: scale(8),
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: wScale(88),
  },

  btnPrimaryText: {
    color: colors.white,
    fontWeight: '600',
    fontSize: fontSize.size14 || 14,
    textAlign: 'center',
  },

  btnSecondary: {
    paddingVertical: hScale(8),
    paddingHorizontal: wScale(12),
    borderRadius: scale(8),
    borderWidth: scale(1),
    borderColor: colors.blue || '#9CA3AF',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    borderRadius: scale(12),
    backgroundColor: colors.blue,
  },

  btnSecondaryText: {
    color: colors.black,
    fontWeight: '500',
    fontSize: fontSize.size14 || 14,
    textAlign: 'center',
  },
  gpsCard: {
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: scale(16),
    paddingBottom: scale(12),
  },
  gpsLeft: {
    flex: 1,
    marginBottom: scale(8),
    justifyContent: 'space-between',
    width: '100%',
  },
  gpsRight: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gpsLabel: {
    fontSize: fontSize.size16,
    color: colors.black,
    marginBottom: scale(4),
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(24),
  },
  gpsValue: {
    fontSize: fontSize.size16,
    color: '#525252',
    marginBottom: scale(4),
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(24),
  },
  gpsTime: {
    fontSize: fontSize.size16,
    color: colors.black,
    marginBottom: scale(4),
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(24),
  },
  btnUpdate: {
    width: '100%',
    borderRadius: scale(8),
    borderWidth: scale(1.5),
    borderColor: '#2563EB', // blue border
    paddingVertical: scale(10),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  btnUpdateText: {
    color: '#2563EB',
    fontWeight: '600',
    fontSize: scale(14),
  },
});

const styleFormCustomer = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    backgroundColor: colors.graySystem2,
    height: height + scale(100),
  },
  containerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  containerHeader1: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: scale(16),
  },
  header1: {
    fontSize: fontSize.size20,
    fontWeight: '600',
    lineHeight: scale(22),
    fontFamily: 'Inter-SemiBold',
    color: colors.black,
    marginTop: scale(0),
    marginHorizontal: scale(12),
    marginBottom: scale(0),
  },
  header: {
    fontSize: fontSize.size16,
    fontWeight: '600',
    lineHeight: scale(24),
    fontFamily: 'Inter-SemiBold',
    color: colors.black,
    marginTop: scale(16),
    marginHorizontal: scale(12),
    marginBottom: scale(12),
  },
  btnShowInfor: {
    marginRight: scale(12),
  },
  card: {
    backgroundColor: colors.white,
    paddingBottom: scale(8),
  },
  cardView: {
    backgroundColor: colors.white,
    paddingBottom: scale(8),
    margin: scale(16),
    borderRadius: scale(12),
  },
  cardFooter: {
    backgroundColor: colors.white,
    paddingBottom: scale(8),
    marginBottom: scale(16),
  },
  cardFooter1: {
    backgroundColor: colors.white,
    paddingTop: scale(8),
    paddingBottom: scale(8),
    // marginBottom: scale(16),
    marginHorizontal: scale(16),
    marginVertical: scale(8),
    borderRadius: scale(12),
  },
  input: {
    marginHorizontal: scale(12),
    marginVertical: scale(4),
  },
  txtHeaderInputView: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
  },
  inputView: {
    borderRadius: scale(8),
    paddingLeft: scale(10),
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    marginTop: scale(8),
    borderWidth: scale(1),
    borderColor: '#D1D3DB',
    backgroundColor: '#E5E7EB',
    paddingVertical: scale(10),
    color: colors.black,
  },
  txtHeaderCompany: {
    fontSize: fontSize.size16,
    fontWeight: '600',
    lineHeight: scale(24),
    fontFamily: 'Inter-SemiBold',
    color: colors.blue,
    marginHorizontal: scale(12),
    marginVertical: scale(8),
  },
  containerFile: {
    padding: scale(8),
  },
  optionsModal: {
    margin: 0,
    justifyContent: 'flex-end',
    borderTopRightRadius: scale(8),
    borderTopLeftRadius: scale(8),
  },
  optionsModalContainer: {
    backgroundColor: colors.white,
    height: 'auto',
    borderTopRightRadius: scale(12),
    borderTopLeftRadius: scale(12),
  },
  containerFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    padding: 8,
    alignItems: 'center',
    zIndex: 1,
    flexDirection: 'row',
  },
  btnConfirm: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.blue,
    borderRadius: scale(8),
    height: hScale(38),
    marginHorizontal: scale(12),
    width: '48%',
    marginBottom: Platform.OS === 'android' ? 0 : scale(16),
  },
  txtBtnConfirm: {
    color: colors.white,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
  },
  btnSave: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: scale(8),
    height: hScale(38),
    width: '48%',
    borderColor: colors.borderColor,
    borderWidth: scale(1),
    marginBottom: Platform.OS === 'android' ? 0 : scale(16),
  },
  txtBtnSave: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
  },
  containerFlat: {
    borderWidth: scale(1),
    borderColor: colors.graySystem2,
    marginHorizontal: scale(12),
    marginVertical: scale(8),
    borderRadius: scale(8),
  },
  containerCheckbox: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(12),
    paddingVertical: scale(8),
  },
  categoryValue: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(Platform.OS === 'android' ? 22 : 26),
    marginLeft: scale(12),
    width: '90%',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.borderColor,
    paddingBottom: scale(Platform.OS === 'android' ? 4 : 0),
  },
  headerBoxImage: {
    fontSize: fontSize.size14,
    lineHeight: scale(22),
    fontFamily: 'Inter-Medium',
    fontWeight: '500',
    color: colors.black,
    marginHorizontal: scale(12),
    marginTop: scale(4),
  },
  imgBox: {
    marginHorizontal: scale(12),
  },
  txtHeaderBody: {
    color: '#6B7280',
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
  },

  contentCard: {
    marginBottom: scale(8),
  },
  contentCardRow: {
    marginBottom: scale(8),
    flexDirection: 'row',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.gray300,
    justifyContent: 'space-between',
    paddingBottom: scale(10),
    paddingHorizontal: scale(0),
  },
  contentBodyDetail: {
    fontSize: fontSize.size14,
    fontWeight: '500',
    lineHeight: scale(22),
    fontFamily: 'Inter-Medium',
    color: colors.black,
    marginLeft: scale(4),
    textAlign: 'right',
  },
  mrh8: {
    height: scale(8),
    width: '100%',
  },
  contentCardRow: {
    marginBottom: scale(8),
    borderBottomWidth: scale(1),
    borderBottomColor: colors.gray300,
    paddingBottom: scale(10),
    paddingHorizontal: scale(0),
    // Thay đổi flexDirection thành column khi text dài
    flexDirection: 'column',
  },

  contentRowFlex: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: scale(8),
    paddingBottom: scale(10),
    paddingHorizontal: scale(0),
    borderBottomWidth: scale(1),
    borderBottomColor: colors.gray300,
  },

  txtHeaderBody: {
    color: colors.black,
    fontSize: fontSize.size16,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    maxWidth: '46%',
  },
  txtHeaderBody1: {
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    minWidth: '46%',
    justifyContent: 'flex-start',
  },
  txtHeaderBodyViewCol: {
    color: colors.black,
    fontSize: fontSize.size16,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    maxWidth: '100%',
  },
  contentBodyDetail: {
    fontSize: fontSize.size16,
    fontWeight: '400',
    lineHeight: scale(22),
    fontFamily: 'Inter-Regular',
    color: colors.gray52,
    marginLeft: scale(4),
    // Thay đổi textAlign và width
    textAlign: 'right',
    width: '100%',
  },

  // Thêm style cho trường hợp text dài
  contentBodyDetailLong: {
    fontSize: fontSize.size16,
    fontWeight: '400',
    lineHeight: scale(22),
    fontFamily: 'Inter-Regular',
    color: colors.gray52,
    marginTop: scale(4), // Thêm margin top khi hiển thị dọc
    width: '100%', // Chiếm full width khi hiển thị dọc
  },
  // add these to your styles object
  gpsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: scale(12),
    paddingVertical: scale(12),
    backgroundColor: '#fff',
    borderRadius: scale(12),
    marginTop: scale(12),
    borderColor: '#EEF2FF', // subtle border
    borderWidth: scale(1),
    // shadow for iOS
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.06,
    shadowRadius: 6,
    // elevation for Android
    elevation: 1,
  },
  gpsLeft: {
    flex: 1,
    paddingRight: scale(8),
  },
  gpsRight: {
    width: scale(160),
    alignItems: 'center',
    justifyContent: 'center',
  },
  gpsLabel: {
    fontSize: scale(12),
    color: '#111827',
    marginBottom: scale(4),
    fontWeight: '500',
  },
  gpsValue: {
    fontSize: scale(14),
    color: '#374151',
    fontWeight: '600',
    marginBottom: scale(6),
  },
  gpsTime: {
    fontSize: scale(12),
    color: '#6B7280',
  },
  btnUpdate: {
    width: '100%',
    borderRadius: scale(8),
    borderWidth: scale(1.5),
    borderColor: colors.blue,
    paddingVertical: scale(10),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    paddingVertical: scale(10),
  },
  btnUpdateText: {
    color: '#2563EB',
    fontWeight: '600',
    fontSize: scale(14),
  },
});

export {styles, styleFormCustomer};
