import {Dimensions, Platform, StyleSheet} from 'react-native';
import {hScale, scale, wScale} from '@resolutions';
import {colors, fontSize} from 'themes';

const {height, width} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  containerSearch: {
    backgroundColor: colors.white,
    width: '100%',
    paddingBottom: scale(10),
    paddingTop: scale(10),
  },
  search: {
    marginHorizontal: scale(12),
  },
  scrollView: {
    backgroundColor: colors.graySystem2,
    height: '100%',
  },
  containerBody: {
    height: '100%',
  },
  imgEmpty: {
    alignSelf: 'center',
    marginTop: scale(24),
  },
  txtHeaderNodata: {
    color: colors.black,
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    alignSelf: 'center',
    lineHeight: scale(24),
    marginTop: scale(16),
  },
  txtContent: {
    marginTop: scale(4),
    alignSelf: 'center',
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: fontSize.size14,
    lineHeight: scale(22),
    color: '#525252',
  },
  imgEmpty: {
    alignSelf: 'center',
    marginTop: scale(24),
  },
  cardProgram: {
    backgroundColor: colors.white,
    marginHorizontal: scale(12),
    marginTop: scale(8),
    borderRadius: scale(8),
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    paddingHorizontal: scale(8),
  },
  headerCustomer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerProgram: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
    marginTop: scale(8),
  },
  containerBody: {
    flexDirection: 'row',
    marginBottom: scale(4),
  },
  containerBodyText: {
    marginBottom: scale(4),
  },
  txtProposal: {
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    color: colors.black,
  },
  bodyCard: {
    marginVertical: scale(8),
  },
  txtHeaderBody: {
    color: '#6B7280',
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
  },
  contentBody: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
  },
  containerFooterCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: scale(8),
  },
  contentTimeApproval: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
  },
  bodyStatus: {
    borderRadius: scale(4),
    paddingHorizontal: scale(6),
    paddingVertical: scale(2),
    width: 'auto',
  },
  txtStatus: {
    fontSize: fontSize.size12,
    fontWeight: '500',
    lineHeight: scale(18),
    fontFamily: 'Inter-Medium',
  },
  btnAdd: {
    position: 'absolute',
    zIndex: 1,
    bottom: scale(Platform.OS === 'ios' ? 16 : 0),
    right: scale(10),
    height: hScale(38),
    width: wScale(38),
    backgroundColor: colors.blue,
    borderRadius: scale(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  flatListContainer: {
    paddingBottom: scale(200),
  },
  modal: {
    margin: 0,
    justifyContent: 'flex-end',
  },
  optionsModalContainer: {
    height: 'auto',
  },
  modalContainer: {
    overflow: 'hidden',
    backgroundColor: colors.white,
    paddingHorizontal: scale(12),
  },
  headerModal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.graySystem2,
    backgroundColor: colors.white,
    borderTopLeftRadius: scale(12),
    borderTopRightRadius: scale(12),
    paddingVertical: scale(10),
    paddingHorizontal: scale(12),
  },
  titleModal: {
    fontFamily: 'Inter-SemiBold',
    fontSize: fontSize.size16,
    lineHeight: scale(24),
    fontWeight: '600',
    color: colors.black,
    flex: 1,
    textAlign: 'center',
  },
  footer: {
    backgroundColor: colors.white,
    borderTopColor: colors.borderColor,
    borderTopWidth: scale(1),
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: scale(12),
    paddingVertical: scale(8),
    // marginBottom:scale(16)
  },
  btnFooterCancel: {
    flex: 1,
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    height: hScale(38),
    borderRadius: scale(8),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(4),
    marginBottom: scale(Platform.OS === 'android' ? 0 : 16),
  },
  txtBtnFooterCancel: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
  },
  btnFooterApproval: {
    flex: 1,
    backgroundColor: colors.blue,
    height: hScale(38),
    borderRadius: scale(8),
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: scale(4),
    marginBottom: scale(Platform.OS === 'android' ? 0 : 16),
  },
  txtBtnFooterApproval: {
    color: colors.white,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
  },
  headerBoxImage: {
    fontSize: fontSize.size14,
    lineHeight: scale(22),
    fontFamily: 'Inter-Medium',
    fontWeight: '500',
    color: colors.black,
    marginTop: scale(4),
  },
  imgBox: {},
  headerInput: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
    marginBottom: scale(4),
    marginTop: scale(8),
  },
  inputContent: {
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    paddingHorizontal: scale(12),
    paddingVertical: scale(8),
    borderRadius: scale(8),
    fontSize: fontSize.size14,
    lineHeight: scale(22),
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    color: colors.black,
    textAlignVertical: 'top',
    backgroundColor: '#F9FAFB',
    marginBottom: scale(8),
  },
});

const stylesFormOrder = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    backgroundColor: colors.graySystem2,
    height: height,
  },
  footerScroll: {
    paddingBottom: scale(300),
  },
  header: {
    fontSize: fontSize.size16,
    fontWeight: '600',
    lineHeight: scale(24),
    fontFamily: 'Inter-SemiBold',
    color: colors.black,
    marginTop: scale(12),
    marginHorizontal: scale(12),
    marginBottom: scale(4),
  },
  card: {
    paddingBottom: scale(8),
    backgroundColor: colors.white,
    marginTop: scale(8),
  },
  headerCard: {
    fontSize: fontSize.size16,
    fontWeight: '600',
    lineHeight: scale(24),
    fontFamily: 'Inter-SemiBold',
    color: colors.blue,
    marginTop: scale(12),
    marginHorizontal: scale(12),
    marginBottom: scale(4),
  },
  inputAuto: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: scale(4),
  },
  widthInput: {
    flex: 1,
    marginHorizontal: scale(12),
  },
  input: {
    marginHorizontal: scale(12),
    marginVertical: scale(4),
  },
  txtHeaderInputView: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
  },
  inputView: {
    borderRadius: scale(8),
    paddingLeft: scale(10),
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    marginTop: scale(8),
    borderWidth: scale(1),
    borderColor: '#D1D3DB',
    backgroundColor: '#E5E7EB',
    paddingVertical: scale(8),
    color: colors.black,
    overflow: 'hidden',
  },
  modal: {
    margin: 0,
    justifyContent: 'flex-end',
  },
  modalContainer: {
    width: width,
    height: hScale(200),
    bottom: 0,
    position: 'absolute',
    backgroundColor: colors.white,
    borderTopLeftRadius: scale(12),
    borderTopRightRadius: scale(12),
  },
  headerModal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.graySystem2,
    backgroundColor: colors.white,
    borderTopLeftRadius: scale(8),
    borderTopRightRadius: scale(8),
    paddingVertical: scale(6),
    paddingHorizontal: scale(12),
  },
  titleModal: {
    fontFamily: 'Inter-SemiBold',
    fontSize: fontSize.size16,
    lineHeight: scale(24),
    fontWeight: '600',
    color: colors.black,
    flex: 1,
    textAlign: 'center',
  },
  btnFooterModal: {
    alignItems: 'center',
    backgroundColor: colors.red,
    borderRadius: scale(8),
    height: hScale(38),
    paddingVertical: scale(Platform.OS === 'android' ? 6 : 8),
    marginTop: scale(12),
    marginBottom: scale(Platform.OS === 'ios' ? 24 : 12),
  },
  date: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnConfirm: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.blue,
    borderRadius: scale(8),
    height: hScale(38),
    marginHorizontal: scale(12),
    width: '48%',
  },
  txtBtnConfirm: {
    color: colors.white,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
  },
  btnSave: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: scale(8),
    height: hScale(38),
    width: '48%',
    borderColor: colors.borderColor,
    borderWidth: scale(1),
  },
  txtBtnSave: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
  },
  optionsModal: {
    margin: 0,
    justifyContent: 'flex-end',
    borderTopRightRadius: scale(8),
    borderTopLeftRadius: scale(8),
  },
  optionsModalContainer: {
    backgroundColor: colors.white,
    height: 'auto',
    borderTopRightRadius: scale(12),
    borderTopLeftRadius: scale(12),
  },
  contentContainer: {
    height: 'auto',
  },
  txtTotoalOrder: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
    marginVertical: scale(8),
  },
  containerFooter: {
    alignItems: 'center',
    zIndex: 1,
    flexDirection: 'row',
    borderTopWidth: scale(1),
    borderTopColor: colors.borderColor,
    paddingVertical: scale(8),
    paddingHorizontal: scale(12),
    marginBottom: scale(Platform.OS === 'ios' ? scale(16) : scale(4)),
  },
  sumaryOrder: {
    paddingHorizontal: scale(8),
  },
  containerButtonFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.white,
  },
  inputRead: {
    flex: 1,
    marginHorizontal: scale(12),
    marginBottom: scale(8),
  },
  txtHeaderInputView: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
  },
  inputView: {
    borderRadius: scale(8),
    paddingLeft: scale(10),
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    marginTop: scale(8),
    borderWidth: scale(1),
    borderColor: '#D1D3DB',
    backgroundColor: '#E5E7EB',
    paddingVertical: scale(10),
    color: colors.black,
  },
  containerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  containerHeaderFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  header: {
    fontSize: fontSize.size16,
    fontWeight: '600',
    lineHeight: scale(24),
    fontFamily: 'Inter-SemiBold',
    color: colors.black,
    marginTop: scale(12),
    marginHorizontal: scale(12),
    marginBottom: scale(4),
  },
  btnShowInfor: {
    marginRight: scale(12),
  },
  containerFlat: {},
  containerCheckbox: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(12),
    paddingVertical: scale(8),
  },
  categoryValue: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    marginLeft: scale(4),
  },
  btnAdd: {
    borderWidth: scale(1),
    borderColor: colors.blue,
    paddingVertical: scale(3),
    borderRadius: scale(4),
    marginRight: scale(12),
    paddingHorizontal: scale(8),
  },
  txtAdd: {
    color: colors.blue,
    fontSize: fontSize.size12,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(12),
  },
  txtCreditCheck: {
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    color: '#525252',
  },
  txtMonney: {
    fontSize: fontSize.size14,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
    color: colors.black,
  },
  bodyStatus: {
    borderRadius: scale(4),
    paddingHorizontal: scale(6),
    paddingVertical: scale(2),
    width: 'auto',
  },
  txtStatus: {
    fontSize: fontSize.size12,
    fontWeight: '500',
    lineHeight: scale(18),
    fontFamily: 'Inter-Medium',
  },
  containerStatus: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: scale(8),
  },
  containerTableFile: {
    marginBottom: scale(8),
    backgroundColor: colors.white,
    paddingHorizontal: scale(12),
    paddingVertical: scale(8),
  },
  tableWrapper: {
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    borderRadius: scale(8),
    overflow: 'hidden',
  },
  row: {
    flexDirection: 'row',
    backgroundColor: '#F9F9FB',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.borderColor,
  },
  headerProgram: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
    marginTop: scale(8),
  },
  rowTable: {
    flexDirection: 'row',
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    marginBottom: scale(8),
  },
  cell_40: {
    width: '28%',
    justifyContent: 'center',
    padding: scale(8),
  },
  cell_20: {
    width: '16%',
    justifyContent: 'center',
    alignItems: 'flex-end',
    padding: scale(8),
  },
  cell_25: {
    width: '20%',
    justifyContent: 'center',
    alignItems: 'flex-end',
    padding: scale(8),
  },
  cell_30: {
    width: '30%',
    justifyContent: 'center',
    alignItems: 'flex-end',
    padding: scale(8),
  },
  txtHeaderTable: {
    color: '#6B7280',
    fontSize: fontSize.size12,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(18),
  },
  containerHeaderTable: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginHorizontal: scale(8),
    marginTop: scale(8),
    width: '100%',
    flexWrap: 'wrap',
  },
  txtValueHeaderTable: {
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: fontSize.size12,
    lineHeight: scale(18),
    color: colors.black,
  },
  txtValueNoteTable: {
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: fontSize.size12,
    lineHeight: scale(18),
    color: '#525252',
  },
  txtValueTable: {
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: fontSize.size12,
    lineHeight: scale(18),
    color: colors.black,
  },
  lastCell: {
    borderBottomWidth: 0,
  },
  cellResponse: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.borderColor,
  },
});

const stylesDetail = StyleSheet.create({
  container: {
    flex: 1,
  },
  containerDetail: {
    paddingBottom: scale(200),
  },
  scrollView: {
    backgroundColor: colors.graySystem2,
    height: height,
  },
  cardFooter1: {
    backgroundColor: colors.white,
    paddingTop: scale(0),
    paddingBottom: scale(8),
    // marginBottom: scale(16),
    marginHorizontal: scale(0),
    marginVertical: scale(0),
    borderRadius: scale(12),
  },
  containerBody: {
    height: height,
    // paddingBottom: scale(200)
  },
  containerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  containerBodyCard: {
    flex: 1,
    marginBottom: scale(8),
  },
  cardProgram: {
    backgroundColor: colors.white,
    paddingHorizontal: scale(12),
  },
  cardFooter: {
    backgroundColor: colors.white,
    paddingHorizontal: scale(12),
    paddingBottom: scale(8),
  },
  headerProgram: {
    color: colors.blue,
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(24),
    marginVertical: scale(8),
  },
  headerModalApproval: {
    color: colors.black,
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(24),
    marginVertical: scale(8),
    textAlign: 'center',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.borderColor,
    paddingVertical: scale(8),
  },
  containerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  header: {
    fontSize: fontSize.size16,
    fontWeight: '600',
    lineHeight: scale(24),
    fontFamily: 'Inter-SemiBold',
    color: colors.black,
    marginTop: scale(12),
    marginHorizontal: scale(12),
    marginBottom: scale(4),
  },
  btnShowInfor: {
    marginRight: scale(12),
  },
  bodyStatus: {
    borderRadius: scale(4),
    paddingHorizontal: scale(6),
    paddingVertical: scale(2),
    width: 'auto',
    marginTop: scale(8),
  },
  txtStatus: {
    fontSize: fontSize.size12,
    fontWeight: '500',
    lineHeight: scale(18),
    fontFamily: 'Inter-Medium',
  },
  bodyCard: {
    marginVertical: scale(8),
  },
  txtHeaderBody: {
    color: '#6B7280',
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
  },
  contentBody: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
  },
  tableWrapper: {
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    borderRadius: scale(8),
    overflow: 'hidden',
    marginTop: scale(8),
  },
  rowTable: {
    borderTopWidth: scale(0),
  },
  cellResponse: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.borderColor,
  },
  valueRow: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    overflow: 'hidden',
  },
  containerRadio: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  title: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    width: '90%',
    marginLeft: scale(4),
  },
  headerInput: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
    marginBottom: scale(4),
    marginHorizontal: scale(12),
  },
  inputContent: {
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    height: hScale(42),
    paddingHorizontal: scale(8),
    paddingVertical: scale(12),
    borderRadius: scale(8),
    fontSize: fontSize.size14,
    lineHeight: scale(22),
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    color: colors.black,
    textAlignVertical: 'top',
    backgroundColor: '#F9FAFB',
    marginTop: scale(8),
  },
  inputNote: {
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    paddingHorizontal: scale(8),
    paddingVertical: scale(12),
    borderRadius: scale(8),
    fontSize: fontSize.size14,
    lineHeight: scale(22),
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    color: colors.black,
    textAlignVertical: 'top',
    backgroundColor: '#F9FAFB',
    marginTop: scale(8),
    marginHorizontal: scale(12),
  },
  containerFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    paddingHorizontal: scale(12),
    paddingVertical: scale(8),
    alignItems: 'center',
    zIndex: 10,
    borderTopWidth: scale(1),
    borderTopColor: colors.borderColor,
    // borderTopColor: colors.borderColor,
  },
  btnFooter: {
    backgroundColor: colors.blue,
    height: hScale(38),
    width: '100%',
    justifyContent: 'center',
    alignContent: 'center',
    borderRadius: scale(8),
    marginBottom: scale(Platform.OS === 'android' ? 0 : 16),
  },
  txtBtnFooter: {
    fontSize: fontSize.size16,
    lineHeight: scale(24),
    fontFamily: 'Inter-SemiBold',
    fontWeight: '600',
    color: colors.white,
    textAlign: 'center',
  },
  row: {
    flexDirection: 'row',
    backgroundColor: '#F9F9FB',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.borderColor,
  },
  cell_table: {
    width: '25%',
    alignItems: 'flex-end',
    justifyContent: 'center',
    padding: scale(8),
  },
  cell_table1: {
    width: '75%',
    alignItems: 'flex-start',
    justifyContent: 'center',
    padding: scale(8),
    paddingHorizontal: scale(12),
  },
  lastCell: {
    borderBottomWidth: 0,
  },
  txtHeaderTable: {
    color: '#6B7280',
    fontSize: fontSize.size12,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(18),
  },
  txtValueTable: {
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: fontSize.size12,
    lineHeight: scale(18),
    color: colors.black,
  },
  optionsModal: {
    margin: 0,
    height: 'auto',
    justifyContent: 'flex-end',
    borderTopRightRadius: scale(8),
    borderTopLeftRadius: scale(8),
  },
  optionsModalContainer: {
    backgroundColor: colors.white,
    height: 'auto',
    borderTopRightRadius: scale(12),
    borderTopLeftRadius: scale(12),
  },
  containerFooterModal: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    paddingHorizontal: scale(16),
    zIndex: 1,
    borderTopWidth: scale(1),
    borderTopColor: colors.borderColor,
    borderTopColor: colors.borderColor,
  },
  btnFooterModal: {
    backgroundColor: colors.blue,
    borderRadius: scale(8),
    height: hScale(38),
    marginTop: scale(12),
    marginBottom: scale(Platform.OS === 'ios' ? 24 : 12),
    justifyContent: 'center',
    alignContent: 'center',
  },
  txtBtnFooterModal: {
    color: colors.white,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
    textAlign: 'center',
  },
  cardProgramModal: {
    backgroundColor: colors.white,
    paddingBottom: scale(80),
  },
  containerInput: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: scale(8),
  },
  input: {
    flex: 1,
    marginHorizontal: scale(12),
  },
  inputView: {
    borderRadius: scale(8),
    paddingLeft: scale(10),
    height: hScale(42),
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
    marginTop: scale(8),
    borderWidth: scale(1),
    borderColor: '#D1D3DB',
    backgroundColor: '#E5E7EB',
    paddingVertical: scale(7),
    color: colors.black,
  },
  containerImage: {
    marginBottom: scale(8),
  },
  containerFormFeedback: {
    marginTop: scale(12),
    marginBottom: scale(8),
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
});
export {styles, stylesDetail, stylesFormOrder};
