import {Dimensions, Platform, StyleSheet} from 'react-native';
import {hScale, scale, wScale} from '@resolutions';
import {colors, fontSize} from 'themes';

const {height} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    backgroundColor: colors.graySystem2,
  },
  containerBody: {
    height: '100%',
  },
  cardFilter: {
    marginTop: scale(8),
    marginHorizontal: scale(12),
  },
  containerSearch: {
    backgroundColor: colors.white,
    width: '100%',
    paddingBottom: scale(10),
    paddingTop: scale(10),
  },
  search: {
    marginHorizontal: scale(12),
  },
});

const stylesAllApproval = StyleSheet.create({
  container: {
    paddingBottom: scale(250),
  },
  scrollview: {},
  imgEmpty: {
    alignSelf: 'center',
    marginTop: scale(24),
  },
  txtHeaderNodata: {
    color: colors.black,
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    alignSelf: 'center',
    fontStyle: 'normal',
    lineHeight: scale(24),
    marginTop: scale(16),
  },
  txtContent: {
    marginTop: scale(4),
    alignSelf: 'center',
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: fontSize.size14,
    lineHeight: scale(22),
    color: '#525252',
  },
  imgEmpty: {
    alignSelf: 'center',
    marginTop: scale(24),
  },
});

const stylesDetail = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    height: height,
    backgroundColor: colors.graySystem2,
  },
  flatScroll: {
    paddingBottom: scale(200),
  },
  containerBody: {
    flexGrow: 1,
    paddingBottom: scale(200),
  },
  cardProgram: {
    backgroundColor: colors.white,
    paddingHorizontal: scale(8),
    paddingBottom: scale(8),
    paddingTop: scale(8),
    borderRadius: scale(8),
    marginHorizontal: scale(12),
    marginTop: scale(8),
    borderWidth: scale(1),
    borderColor: colors.borderColor,
  },
  headerModalApproval: {
    color: colors.black,
    fontSize: fontSize.size16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(24),
    marginVertical: scale(8),
    textAlign: 'center',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.borderColor,
    paddingVertical: scale(8),
  },
  containerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  header: {
    fontSize: fontSize.size14,
    fontWeight: '600',
    lineHeight: scale(22),
    fontFamily: 'Inter-SemiBold',
    color: colors.black,
    width: '70%',
    overflow: 'hidden',
  },
  card: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: scale(10),
    alignItems: 'center',
    width: '55%',
  },
  headerInput: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
    marginBottom: scale(4),
  },
  inputNote: {
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    paddingHorizontal: scale(8),
    paddingVertical: scale(12),
    borderRadius: scale(8),
    fontSize: fontSize.size14,
    lineHeight: scale(22),
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    color: colors.black,
    textAlignVertical: 'top',
    backgroundColor: '#F9FAFB',
    marginTop: scale(8),
    marginHorizontal: scale(12),
  },
  headerInputForm: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
    marginBottom: scale(4),
    marginTop: scale(8),
  },
  inputContent: {
    borderWidth: scale(1),
    borderColor: colors.borderColor,
    paddingHorizontal: scale(12),
    paddingVertical: scale(8),
    borderRadius: scale(8),
    fontSize: fontSize.size14,
    lineHeight: scale(22),
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    color: colors.black,
    textAlignVertical: 'top',
    backgroundColor: '#F9FAFB',
    marginBottom: scale(8),
  },
  bodyStatus: {
    borderRadius: scale(4),
    paddingHorizontal: scale(6),
    paddingVertical: scale(2),
    width: 'auto',
  },
  txtStatus: {
    fontSize: fontSize.size12,
    fontWeight: '500',
    lineHeight: scale(18),
    fontFamily: 'Inter-Medium',
  },
  containerBodyCard: {
    flex: 1,
    marginBottom: scale(4),
  },
  txtHeaderBody: {
    color: '#525252',
    fontSize: fontSize.size14,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    lineHeight: scale(22),
  },
  contentBody: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
  },
  containerContentBody: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  containerFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    paddingHorizontal: scale(12),
    paddingVertical: scale(8),
    alignItems: 'center',
    zIndex: 10,
    borderTopWidth: scale(1),
    borderTopColor: colors.borderColor,
    borderTopColor: colors.borderColor,
  },
  btnFooter: {
    backgroundColor: colors.blue,
    height: hScale(38),
    width: '100%',
    justifyContent: 'center',
    alignContent: 'center',
    borderRadius: scale(8),
    marginBottom: scale(Platform.OS === 'android' ? 0 : 16),
  },
  txtBtnFooter: {
    fontSize: fontSize.size16,
    lineHeight: scale(24),
    fontFamily: 'Inter-SemiBold',
    fontWeight: '600',
    color: colors.white,
    textAlign: 'center',
  },
  optionsModal: {
    margin: 0,
    height: 'auto',
    justifyContent: 'flex-end',
    borderTopRightRadius: scale(8),
    borderTopLeftRadius: scale(8),
  },
  optionsModalContainer: {
    backgroundColor: colors.white,
    height: 'auto',
    borderTopRightRadius: scale(12),
    borderTopLeftRadius: scale(12),
  },
  cardProgramModal: {
    backgroundColor: colors.white,
    paddingBottom: scale(80),
  },
  txtHeaderInputView: {
    color: colors.black,
    fontSize: fontSize.size14,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    lineHeight: scale(22),
    marginHorizontal: scale(12),
  },
  containerFooterModal: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    paddingHorizontal: scale(16),
    zIndex: 1,
    borderTopWidth: scale(1),
    borderTopColor: colors.borderColor,
    borderTopColor: colors.borderColor,
  },
  btnFooterModal: {
    backgroundColor: colors.blue,
    borderRadius: scale(8),
    height: hScale(38),
    marginTop: scale(12),
    marginBottom: scale(Platform.OS === 'ios' ? 24 : 12),
    justifyContent: 'center',
    alignContent: 'center',
  },
  txtBtnFooterModal: {
    color: colors.white,
    fontSize: fontSize.size14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    lineHeight: scale(22),
    textAlign: 'center',
  },
  loading: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnExtend: {
    position: 'absolute',
    right: wScale(20),
    top: wScale(10),
    backgroundColor: 'white',
    padding: 0,
    zIndex: 999,
  },
  btnClose: {
    position: 'absolute',
    right: wScale(0),
    top: wScale(20),
    padding: wScale(10),
    borderRadius: scale(8),
    backgroundColor: 'transparent',
    borderColor: colors.gray300,
    borderWidth: scale(1),
    zIndex: 999,
  },
  btnDownLoad: {
    position: 'absolute',
    right: wScale(0),
    bottom: wScale(30),
    padding: wScale(4),
    borderRadius: scale(8),
    backgroundColor: 'transparent',
    borderColor: colors.gray300,
    borderWidth: scale(1),
    zIndex: 999,
  },
});

const stylesProgress = StyleSheet.create({
  container: {
    flex: 1,
    padding: scale(16),
    backgroundColor: '#fff',
    height: height,
  },
  list: {
    paddingBottom: scale(16),
  },
  itemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  circle: {
    width: scale(16),
    height: scale(16),
    borderRadius: 10,
    backgroundColor: '#D1D3DB',
    position: 'absolute',
  },
  line: {
    width: scale(4),
    height: scale(50),
    backgroundColor: '#D1D3DB',
    position: 'absolute',
    left: scale(6),
    top: scale(22),
  },
  line2: {
    width: scale(4),
    height: scale(88),
    backgroundColor: '#D1D3DB',
    position: 'absolute',
    left: scale(6),
    top: scale(20),
  },
  stopText: {
    marginLeft: scale(30),
    fontSize: fontSize.size14,
    fontWeight: '600',
    lineHeight: scale(22),
    fontFamily: 'Inter-Regular',
    color: colors.black,
  },
  txtDate: {
    marginTop: scale(8),
    fontSize: fontSize.size12,
    lineHeight: scale(18),
    fontFamily: 'Inter-Regular',
    color: colors.gray600,
    fontWeight: '400',
    marginLeft: scale(30),
    marginBottom: scale(4),
  },
  txtApprove: {
    fontSize: fontSize.size12,
    lineHeight: scale(18),
    fontFamily: 'Inter-Regular',
    color: colors.black,
    fontWeight: '400',
    marginLeft: scale(30),
    marginBottom: scale(8),
  },
});

export {styles, stylesAllApproval, stylesDetail, stylesProgress};
